name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
- push
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.9'
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    - name: Test Linear Regression
      id: test-ols
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Linear Regression
        setup-command: ''
        command: python -m unittest tests/testLinearRegression.py
        timeout: 3
        max-score: 1
    - name: Test Logistic Regression
      id: test-logit
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Logistic Regression
        setup-command: ''
        command: python -m unittest tests/testLogisticRegression.py
        timeout: 3
        max-score: 1
    - name: Test Random Forest
      id: test-forest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Random Forest
        setup-command: ''
        command: python -m unittest tests/testRandomForest.py
        timeout: 3
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-OLS_RESULTS: "${{steps.test-ols.outputs.result}}"
        TEST-LOGIT_RESULTS: "${{steps.test-logit.outputs.result}}"
        TEST-FOREST_RESULTS: "${{steps.test-forest.outputs.result}}"
      with:
        runners: test-ols,test-logit,test-forest
